<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>Debentialc</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>local</groupId>
            <artifactId>craftbukkit-1710-R4</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/craftbukkit-1.7.10-R4.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>CustomNPC-Plus-1102</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/CustomNPC-Plus-1.10.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>DragonBlockC-v1485</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/DragonBlockC-v1.4.85.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>Essentials</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/Essentials.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>Factions</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/Factions.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>FeatherBoard</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/FeatherBoard.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>HolographicDisplays</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/HolographicDisplays.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>JBRA-Client-v1652</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/JBRA-Client-v1.6.52.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>JRMCore-v1351</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/JRMCore-v1.3.51.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>lombok</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/lombok.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>MassiveCore</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/MassiveCore.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>nms-stubs</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/nms-stubs.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>minecraft</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/minecraft.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>Multiverse-Core-25</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/Multiverse-Core-2.5.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>npcdbc-112</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/npcdbc-1.1.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>PlaceholderAPI-2115</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/PlaceholderAPI-2.11.5.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>ProtocolLib</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/ProtocolLib.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>rhino-17R4</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/rhino-1.7R4.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>SkinsRestorer-v1044-BETA</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/SkinsRestorer-v10.4.4-BETA.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>SmartInvs-127</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/SmartInvs-1.2.7.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>Vault-141</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/Vault-1.4.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>voicechat-bukkit-2530</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/voicechat-bukkit-2.5.30.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>VoxelSniper-51700-SNAPSHOT</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/VoxelSniper-5.170.0-SNAPSHOT.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>worldedit-bukkit-61</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/worldedit-bukkit-6.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>worldguard-62</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/plugins/worldguard-6.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>local</groupId>
            <artifactId>gson-231</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/jeanf/Downloads/gson-2.3.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.mozilla</groupId>
            <artifactId>rhino</artifactId>
            <version>1.7.14</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                        </manifest>
                    </archive>
                    <includes>
                        <include>plugin.yml</include>
                        <include>**/*.class</include>
                    </includes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>